// src/data/courses.ts

export const courses = [
  /* ===================================================
     TECHNOLOGY (20 Courses)
  =================================================== */

  {
    id: 1,
    category: "Technology",
    skill: "Computer Science",
    title: "Computer Science Fundamentals",
    provider: "SkillSage Tech",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "💻",
    rating: 4.7,
    students: "12,400+",
    description: "Programming basics, algorithms, logic building.",
  },

  {
    id: 2,
    category: "Technology",
    skill: "Computer Science",
    title: "Advanced Computer Systems",
    provider: "SkillSage Tech",
    type: "Paid",
    fee: "₹14,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🖥️",
    rating: 4.8,
    students: "8,900+",
    description: "Operating systems, DBMS, networking.",
  },

  {
    id: 3,
    category: "Technology",
    skill: "AI",
    title: "Artificial Intelligence Starter",
    provider: "SkillSage AI",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Very High",
    level: "Beginner",
    icon: "🤖",
    rating: 4.9,
    students: "22,000+",
    description: "AI basics, prompts, tools, model usage.",
  },

  {
    id: 4,
    category: "Technology",
    skill: "AI",
    title: "AI Engineer Professional",
    provider: "SkillSage AI",
    type: "Paid",
    fee: "₹29,999",
    duration: "9 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🧠",
    rating: 4.9,
    students: "9,300+",
    description: "LLMs, neural networks, deployment projects.",
  },

  {
    id: 5,
    category: "Technology",
    skill: "Data Science",
    title: "Data Analyst Essentials",
    provider: "SkillSage Data",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "📊",
    rating: 4.8,
    students: "18,500+",
    description: "Excel, dashboards, SQL, reporting.",
  },

  {
    id: 6,
    category: "Technology",
    skill: "Data Science",
    title: "Professional Data Science Program",
    provider: "SkillSage Data",
    type: "Paid",
    fee: "₹24,999",
    duration: "8 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "📈",
    rating: 4.9,
    students: "11,700+",
    description: "Python, ML, statistics, real projects.",
  },

  {
    id: 7,
    category: "Technology",
    skill: "Cybersecurity",
    title: "Cybersecurity Fundamentals",
    provider: "SkillSage Secure",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🔐",
    rating: 4.7,
    students: "13,200+",
    description: "Security basics, threats, networks.",
  },

  {
    id: 8,
    category: "Technology",
    skill: "Cybersecurity",
    title: "Ethical Hacking Mastery",
    provider: "SkillSage Secure",
    type: "Paid",
    fee: "₹27,999",
    duration: "8 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🛡️",
    rating: 4.9,
    students: "7,600+",
    description: "Pen testing, Kali Linux, SOC tools.",
  },

  {
    id: 9,
    category: "Technology",
    skill: "Software Engineering",
    title: "Software Developer Career Track",
    provider: "SkillSage Dev",
    type: "Free",
    fee: "Free",
    duration: "5 Months",
    certificate: true,
    demand: "Very High",
    level: "Beginner",
    icon: "👨‍💻",
    rating: 4.8,
    students: "20,100+",
    description: "Coding, OOP, Git, projects.",
  },

  {
    id: 10,
    category: "Technology",
    skill: "Software Engineering",
    title: "Full Stack Engineering Pro",
    provider: "SkillSage Dev",
    type: "Paid",
    fee: "₹21,999",
    duration: "9 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🌐",
    rating: 4.9,
    students: "14,400+",
    description: "Frontend + backend + deployment.",
  },

  {
    id: 11,
    category: "Technology",
    skill: "Cloud",
    title: "Cloud Basics with AWS",
    provider: "SkillSage Cloud",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "☁️",
    rating: 4.7,
    students: "10,500+",
    description: "AWS intro, hosting, storage.",
  },

  {
    id: 12,
    category: "Technology",
    skill: "Cloud",
    title: "Cloud Engineer Professional",
    provider: "SkillSage Cloud",
    type: "Paid",
    fee: "₹25,999",
    duration: "7 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🌩️",
    rating: 4.8,
    students: "8,800+",
    description: "AWS, Azure, CI/CD, architecture.",
  },

  {
    id: 13,
    category: "Technology",
    skill: "UI/UX",
    title: "UI UX Design Starter",
    provider: "SkillSage Design",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🎨",
    rating: 4.7,
    students: "16,300+",
    description: "Figma, wireframes, user flows.",
  },

  {
    id: 14,
    category: "Technology",
    skill: "UI/UX",
    title: "UI UX Product Designer",
    provider: "SkillSage Design",
    type: "Paid",
    fee: "₹18,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🖌️",
    rating: 4.8,
    students: "9,900+",
    description: "Case studies, portfolio, design systems.",
  },

  {
    id: 15,
    category: "Technology",
    skill: "Software Engineering",
    title: "Frontend Developer Bootcamp",
    provider: "SkillSage Dev",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🧩",
    rating: 4.8,
    students: "17,000+",
    description: "HTML, CSS, React, Tailwind.",
  },

  {
    id: 16,
    category: "Technology",
    skill: "Software Engineering",
    title: "Backend Developer Career Path",
    provider: "SkillSage Dev",
    type: "Paid",
    fee: "₹19,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "⚙️",
    rating: 4.8,
    students: "7,900+",
    description: "Node.js, APIs, databases.",
  },

  {
    id: 17,
    category: "Technology",
    skill: "Data Science",
    title: "Business Intelligence Analyst",
    provider: "SkillSage Data",
    type: "Paid",
    fee: "₹16,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "📉",
    rating: 4.7,
    students: "6,200+",
    description: "Power BI, Tableau, analytics.",
  },

  {
    id: 18,
    category: "Technology",
    skill: "Cloud",
    title: "DevOps with Cloud Tools",
    provider: "SkillSage Cloud",
    type: "Paid",
    fee: "₹26,999",
    duration: "8 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🚀",
    rating: 4.9,
    students: "5,700+",
    description: "Docker, CI/CD, Kubernetes.",
  },

  {
    id: 19,
    category: "Technology",
    skill: "AI",
    title: "Generative AI for Business",
    provider: "SkillSage AI",
    type: "Free",
    fee: "Free",
    duration: "2 Months",
    certificate: true,
    demand: "Very High",
    level: "Beginner",
    icon: "✨",
    rating: 4.8,
    students: "25,000+",
    description: "ChatGPT, prompts, automation tools.",
  },

  {
    id: 20,
    category: "Technology",
    skill: "Cybersecurity",
    title: "SOC Analyst Program",
    provider: "SkillSage Secure",
    type: "Paid",
    fee: "₹23,999",
    duration: "7 Months",
    certificate: true,
    demand: "Very High",
    level: "Intermediate",
    icon: "🛰️",
    rating: 4.8,
    students: "4,900+",
    description: "Incident response and monitoring.",
  },

  /* ===================================================
     COMMERCE & BUSINESS (20 Courses)
  =================================================== */

  {
    id: 21,
    category: "Commerce & Business",
    skill: "Finance",
    title: "Finance Basics Certification",
    provider: "SkillSage Biz",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "💰",
    rating: 4.7,
    students: "9,500+",
    description: "Budgeting, accounting basics.",
  },

  {
    id: 22,
    category: "Commerce & Business",
    skill: "Finance",
    title: "Investment Banking Track",
    provider: "SkillSage Biz",
    type: "Paid",
    fee: "₹31,999",
    duration: "10 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🏦",
    rating: 4.9,
    students: "3,800+",
    description: "Corporate finance, markets.",
  },

  {
    id: 23,
    category: "Commerce & Business",
    skill: "Accounting",
    title: "Accounting Essentials",
    provider: "SkillSage Biz",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🧾",
    rating: 4.6,
    students: "11,000+",
    description: "Ledger, GST, Tally basics.",
  },

  {
    id: 24,
    category: "Commerce & Business",
    skill: "Accounting",
    title: "Advanced GST & Taxation",
    provider: "SkillSage Biz",
    type: "Paid",
    fee: "₹14,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "📑",
    rating: 4.8,
    students: "5,600+",
    description: "Tax filing, GST returns.",
  },

  {
    id: 25,
    category: "Commerce & Business",
    skill: "Marketing",
    title: "Digital Marketing Bootcamp",
    provider: "SkillSage Biz",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "📣",
    rating: 4.8,
    students: "17,400+",
    description: "SEO, ads, content creation.",
  },

  {
    id: 26,
    category: "Commerce & Business",
    skill: "Marketing",
    title: "Growth Marketing Pro",
    provider: "SkillSage Biz",
    type: "Paid",
    fee: "₹18,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🚀",
    rating: 4.9,
    students: "6,700+",
    description: "Funnels, analytics, growth hacks.",
  },

  {
    id: 27,
    category: "Commerce & Business",
    skill: "Management",
    title: "Business Management Basics",
    provider: "SkillSage Biz",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "📊",
    rating: 4.6,
    students: "8,800+",
    description: "Operations, planning, teams.",
  },

  {
    id: 28,
    category: "Commerce & Business",
    skill: "Management",
    title: "MBA Readiness Program",
    provider: "SkillSage Biz",
    type: "Paid",
    fee: "₹19,999",
    duration: "8 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🎯",
    rating: 4.8,
    students: "4,300+",
    description: "Leadership + case studies.",
  },

  {
    id: 29,
    category: "Commerce & Business",
    skill: "Entrepreneurship",
    title: "Startup Launchpad",
    provider: "SkillSage Biz",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "💡",
    rating: 4.8,
    students: "14,000+",
    description: "Idea validation and MVP building.",
  },

  {
    id: 30,
    category: "Commerce & Business",
    skill: "Entrepreneurship",
    title: "Founder Accelerator Program",
    provider: "SkillSage Biz",
    type: "Paid",
    fee: "₹28,999",
    duration: "9 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🏆",
    rating: 4.9,
    students: "2,900+",
    description: "Funding, scale, startup systems.",
  },
// PART 2
// Continue inside same courses array
// Starts from id: 31

  /* ===================================================
     SCIENCE (15 Courses)
  =================================================== */

  {
    id: 31,
    category: "Science",
    skill: "Physics",
    title: "Applied Physics Foundations",
    provider: "SkillSage Science",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "⚛️",
    rating: 4.7,
    students: "7,200+",
    description: "Mechanics, motion, energy, lab basics.",
  },

  {
    id: 32,
    category: "Science",
    skill: "Physics",
    title: "Modern Physics Research Program",
    provider: "SkillSage Science",
    type: "Paid",
    fee: "₹17,999",
    duration: "8 Months",
    certificate: true,
    demand: "Medium",
    level: "Advanced",
    icon: "🔭",
    rating: 4.8,
    students: "2,900+",
    description: "Quantum theory, optics, experimentation.",
  },

  {
    id: 33,
    category: "Science",
    skill: "Chemistry",
    title: "Chemistry Essentials",
    provider: "SkillSage Science",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🧪",
    rating: 4.6,
    students: "8,100+",
    description: "Organic, inorganic and reactions.",
  },

  {
    id: 34,
    category: "Science",
    skill: "Chemistry",
    title: "Industrial Chemistry Diploma",
    provider: "SkillSage Science",
    type: "Paid",
    fee: "₹18,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "⚗️",
    rating: 4.8,
    students: "3,400+",
    description: "Manufacturing chemicals and process labs.",
  },

  {
    id: 35,
    category: "Science",
    skill: "Biology",
    title: "Biology Foundations",
    provider: "SkillSage Science",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🧬",
    rating: 4.7,
    students: "9,000+",
    description: "Cells, genetics, human systems.",
  },

  {
    id: 36,
    category: "Science",
    skill: "Biology",
    title: "Biotech Career Program",
    provider: "SkillSage Science",
    type: "Paid",
    fee: "₹22,999",
    duration: "9 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🔬",
    rating: 4.9,
    students: "4,100+",
    description: "Biotech tools, lab projects, research.",
  },

  {
    id: 37,
    category: "Science",
    skill: "Botany",
    title: "Plant Science Certification",
    provider: "SkillSage Science",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🌿",
    rating: 4.5,
    students: "3,800+",
    description: "Plant biology and ecosystems.",
  },

  {
    id: 38,
    category: "Science",
    skill: "Zoology",
    title: "Animal Biology Program",
    provider: "SkillSage Science",
    type: "Paid",
    fee: "₹14,999",
    duration: "6 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "🦋",
    rating: 4.6,
    students: "2,700+",
    description: "Animal systems, species, habitats.",
  },

  {
    id: 39,
    category: "Science",
    skill: "Astronomy",
    title: "Astronomy Explorer",
    provider: "SkillSage Science",
    type: "Free",
    fee: "Free",
    duration: "2 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🌌",
    rating: 4.8,
    students: "10,200+",
    description: "Stars, galaxies, telescopes.",
  },

  {
    id: 40,
    category: "Science",
    skill: "Microbiology",
    title: "Microbiology Lab Basics",
    provider: "SkillSage Science",
    type: "Paid",
    fee: "₹16,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🦠",
    rating: 4.8,
    students: "3,600+",
    description: "Bacteria, viruses, lab techniques.",
  },

  /* ===================================================
     ARTS & CREATIVITY (20 Courses)
  =================================================== */

  {
    id: 41,
    category: "Arts & Creativity",
    skill: "Music",
    title: "Music Production Starter",
    provider: "SkillSage Arts",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🎵",
    rating: 4.8,
    students: "13,500+",
    description: "Composition, rhythm, DAW basics.",
  },

  {
    id: 42,
    category: "Arts & Creativity",
    skill: "Music",
    title: "Professional Singing Academy",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹19,999",
    duration: "8 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🎤",
    rating: 4.9,
    students: "6,800+",
    description: "Vocals, stage performance, recording.",
  },

  {
    id: 43,
    category: "Arts & Creativity",
    skill: "Art",
    title: "Fine Arts Essentials",
    provider: "SkillSage Arts",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🖼️",
    rating: 4.6,
    students: "5,700+",
    description: "Sketching, colors, composition.",
  },

  {
    id: 44,
    category: "Arts & Creativity",
    skill: "Dance",
    title: "Dance Performance Course",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹14,999",
    duration: "6 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "💃",
    rating: 4.8,
    students: "4,600+",
    description: "Technique, choreography, stage skills.",
  },

  {
    id: 45,
    category: "Arts & Creativity",
    skill: "Theatre",
    title: "Theatre Acting Basics",
    provider: "SkillSage Arts",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🎭",
    rating: 4.7,
    students: "4,300+",
    description: "Expression, scripts, character work.",
  },

  {
    id: 46,
    category: "Arts & Creativity",
    skill: "Design",
    title: "Graphic Design Bootcamp",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹17,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🎨",
    rating: 4.9,
    students: "8,900+",
    description: "Photoshop, Illustrator, branding.",
  },

  {
    id: 47,
    category: "Arts & Creativity",
    skill: "Fashion",
    title: "Fashion Styling Program",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹21,999",
    duration: "8 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "👗",
    rating: 4.8,
    students: "3,900+",
    description: "Styling, trend study, portfolio.",
  },

  {
    id: 48,
    category: "Arts & Creativity",
    skill: "Film",
    title: "Film Making Starter",
    provider: "SkillSage Arts",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🎬",
    rating: 4.8,
    students: "7,700+",
    description: "Camera, script, direction basics.",
  },

  {
    id: 49,
    category: "Arts & Creativity",
    skill: "Creative Writing",
    title: "Creative Writing Studio",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹12,999",
    duration: "5 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "✍️",
    rating: 4.7,
    students: "5,100+",
    description: "Storytelling, poetry, publishing.",
  },

  {
    id: 50,
    category: "Arts & Creativity",
    skill: "Design",
    title: "UI Visual Design Mastery",
    provider: "SkillSage Arts",
    type: "Paid",
    fee: "₹18,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🖌️",
    rating: 4.9,
    students: "4,500+",
    description: "Layouts, typography, modern branding.",
  },

  /* ===================================================
     HUMANITIES (10 Courses)
  =================================================== */

  {
    id: 51,
    category: "Humanities",
    skill: "Psychology",
    title: "Psychology Foundations",
    provider: "SkillSage Humanities",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🧠",
    rating: 4.8,
    students: "11,000+",
    description: "Human behavior and cognition.",
  },

  {
    id: 52,
    category: "Humanities",
    skill: "Psychology",
    title: "Counselling Skills Diploma",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹19,999",
    duration: "8 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "💬",
    rating: 4.9,
    students: "5,400+",
    description: "Therapy basics and client handling.",
  },

  {
    id: 53,
    category: "Humanities",
    skill: "Sociology",
    title: "Sociology Essentials",
    provider: "SkillSage Humanities",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "🌍",
    rating: 4.6,
    students: "4,900+",
    description: "Society, culture and communities.",
  },

  {
    id: 54,
    category: "Humanities",
    skill: "History",
    title: "World History Course",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹11,999",
    duration: "5 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "🏺",
    rating: 4.7,
    students: "3,600+",
    description: "Civilizations and modern history.",
  },

  {
    id: 55,
    category: "Humanities",
    skill: "Political Science",
    title: "Political Science & Governance",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹15,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🏛️",
    rating: 4.8,
    students: "4,200+",
    description: "Politics, constitutions, governance.",
  },
  // PART 3
// Continue inside same courses array
// Starts from id: 56

  /* ===================================================
     HUMANITIES (continued)
  =================================================== */

  {
    id: 56,
    category: "Humanities",
    skill: "Philosophy",
    title: "Philosophy & Critical Thinking",
    provider: "SkillSage Humanities",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "Medium",
    level: "Beginner",
    icon: "📚",
    rating: 4.7,
    students: "5,100+",
    description: "Logic, ethics, reasoning foundations.",
  },

  {
    id: 57,
    category: "Humanities",
    skill: "History",
    title: "Modern Indian History Program",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹12,999",
    duration: "5 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "🗺️",
    rating: 4.8,
    students: "3,900+",
    description: "Freedom movement and nation building.",
  },

  {
    id: 58,
    category: "Humanities",
    skill: "Psychology",
    title: "Child Psychology Essentials",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹16,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "👶",
    rating: 4.8,
    students: "4,700+",
    description: "Developmental psychology and learning.",
  },

  {
    id: 59,
    category: "Humanities",
    skill: "Sociology",
    title: "Social Research Methods",
    provider: "SkillSage Humanities",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "📊",
    rating: 4.6,
    students: "2,800+",
    description: "Field surveys and qualitative research.",
  },

  {
    id: 60,
    category: "Humanities",
    skill: "Political Science",
    title: "International Relations Track",
    provider: "SkillSage Humanities",
    type: "Paid",
    fee: "₹18,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🌐",
    rating: 4.9,
    students: "3,200+",
    description: "Global politics, diplomacy, policy.",
  },

  /* ===================================================
     LAW & PUBLIC SERVICE (15 Courses)
  =================================================== */

  {
    id: 61,
    category: "Law & Public Service",
    skill: "Law",
    title: "Law Foundations Certificate",
    provider: "SkillSage Law",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "⚖️",
    rating: 4.8,
    students: "9,600+",
    description: "Legal systems, rights, fundamentals.",
  },

  {
    id: 62,
    category: "Law & Public Service",
    skill: "Law",
    title: "Corporate Law Specialist",
    provider: "SkillSage Law",
    type: "Paid",
    fee: "₹27,999",
    duration: "9 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🏢",
    rating: 4.9,
    students: "4,100+",
    description: "Contracts, compliance, company law.",
  },

  {
    id: 63,
    category: "Law & Public Service",
    skill: "UPSC",
    title: "UPSC Foundation Batch",
    provider: "SkillSage Civil",
    type: "Paid",
    fee: "₹34,999",
    duration: "12 Months",
    certificate: true,
    demand: "Very High",
    level: "Beginner",
    icon: "🏛️",
    rating: 4.9,
    students: "7,400+",
    description: "GS, polity, economy, current affairs.",
  },

  {
    id: 64,
    category: "Law & Public Service",
    skill: "UPSC",
    title: "UPSC Interview Mastery",
    provider: "SkillSage Civil",
    type: "Paid",
    fee: "₹14,999",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🎯",
    rating: 4.8,
    students: "2,300+",
    description: "Mock interviews and personality prep.",
  },

  {
    id: 65,
    category: "Law & Public Service",
    skill: "Governance",
    title: "Governance & Administration",
    provider: "SkillSage Civil",
    type: "Free",
    fee: "Free",
    duration: "5 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "📜",
    rating: 4.7,
    students: "5,500+",
    description: "Public systems and administration.",
  },

  {
    id: 66,
    category: "Law & Public Service",
    skill: "Public Policy",
    title: "Public Policy Analyst Program",
    provider: "SkillSage Civil",
    type: "Paid",
    fee: "₹22,999",
    duration: "8 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "📈",
    rating: 4.8,
    students: "3,000+",
    description: "Policy design, governance strategy.",
  },

  {
    id: 67,
    category: "Law & Public Service",
    skill: "Law",
    title: "Criminal Law Essentials",
    provider: "SkillSage Law",
    type: "Paid",
    fee: "₹16,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🔍",
    rating: 4.7,
    students: "2,900+",
    description: "Criminal justice and procedure.",
  },

  {
    id: 68,
    category: "Law & Public Service",
    skill: "Law",
    title: "Intellectual Property Rights",
    provider: "SkillSage Law",
    type: "Paid",
    fee: "₹18,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "💡",
    rating: 4.8,
    students: "2,500+",
    description: "Patents, trademarks, copyrights.",
  },

  {
    id: 69,
    category: "Law & Public Service",
    skill: "Governance",
    title: "Rural Development Program",
    provider: "SkillSage Civil",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "Medium",
    level: "Intermediate",
    icon: "🌾",
    rating: 4.6,
    students: "3,800+",
    description: "Development models and welfare schemes.",
  },

  {
    id: 70,
    category: "Law & Public Service",
    skill: "Public Policy",
    title: "Urban Policy & Smart Cities",
    provider: "SkillSage Civil",
    type: "Paid",
    fee: "₹17,999",
    duration: "5 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🏙️",
    rating: 4.7,
    students: "2,200+",
    description: "Urban planning and smart governance.",
  },

  /* ===================================================
     HEALTH (15 Courses)
  =================================================== */

  {
    id: 71,
    category: "Health",
    skill: "Medicine",
    title: "Medical Science Foundations",
    provider: "SkillSage Health",
    type: "Free",
    fee: "Free",
    duration: "5 Months",
    certificate: true,
    demand: "Very High",
    level: "Beginner",
    icon: "🩺",
    rating: 4.8,
    students: "8,800+",
    description: "Human anatomy and healthcare basics.",
  },

  {
    id: 72,
    category: "Health",
    skill: "Medicine",
    title: "Clinical Skills Advanced",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹29,999",
    duration: "10 Months",
    certificate: true,
    demand: "Very High",
    level: "Advanced",
    icon: "🏥",
    rating: 4.9,
    students: "3,900+",
    description: "Clinical practice and patient systems.",
  },

  {
    id: 73,
    category: "Health",
    skill: "Nursing",
    title: "Nursing Assistant Program",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹18,999",
    duration: "8 Months",
    certificate: true,
    demand: "Very High",
    level: "Intermediate",
    icon: "💉",
    rating: 4.8,
    students: "4,700+",
    description: "Patient care and hospital workflow.",
  },

  {
    id: 74,
    category: "Health",
    skill: "Pharmacy",
    title: "Pharmacy Foundations",
    provider: "SkillSage Health",
    type: "Free",
    fee: "Free",
    duration: "4 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "💊",
    rating: 4.7,
    students: "5,600+",
    description: "Medicines, dosage, pharmacy basics.",
  },

  {
    id: 75,
    category: "Health",
    skill: "Nutrition",
    title: "Nutrition & Wellness Coach",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹16,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "🥗",
    rating: 4.8,
    students: "6,100+",
    description: "Diet planning and wellness coaching.",
  },

  {
    id: 76,
    category: "Health",
    skill: "Nutrition",
    title: "Sports Nutrition Program",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹19,999",
    duration: "7 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "🏃",
    rating: 4.8,
    students: "2,800+",
    description: "Athlete diet and performance nutrition.",
  },

  {
    id: 77,
    category: "Health",
    skill: "Medicine",
    title: "Emergency Care Basics",
    provider: "SkillSage Health",
    type: "Free",
    fee: "Free",
    duration: "3 Months",
    certificate: true,
    demand: "High",
    level: "Beginner",
    icon: "🚑",
    rating: 4.7,
    students: "7,100+",
    description: "First aid and emergency response.",
  },

  {
    id: 78,
    category: "Health",
    skill: "Nursing",
    title: "Geriatric Care Specialist",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹15,999",
    duration: "5 Months",
    certificate: true,
    demand: "High",
    level: "Intermediate",
    icon: "👵",
    rating: 4.7,
    students: "2,400+",
    description: "Elder care and patient support.",
  },

  {
    id: 79,
    category: "Health",
    skill: "Pharmacy",
    title: "Hospital Pharmacy Operations",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹17,999",
    duration: "6 Months",
    certificate: true,
    demand: "High",
    level: "Advanced",
    icon: "📦",
    rating: 4.8,
    students: "2,100+",
    description: "Drug inventory and operations.",
  },

  {
    id: 80,
    category: "Health",
    skill: "Medicine",
    title: "Medical Coding Career Path",
    provider: "SkillSage Health",
    type: "Paid",
    fee: "₹21,999",
    duration: "8 Months",
    certificate: true,
    demand: "Very High",
    level: "Intermediate",
    icon: "🧾",
    rating: 4.9,
    students: "3,500+",
    description: "Healthcare coding and records systems.",
  },
]